### ISSUE TITLE
Not Working Properly.

### ISSUE THREAD

**Issue by preetmungara** [omkar-pote/count-cuckoo#31]
When I click on extension it shows something like this.

![sshot-012](https://user-images.githubusercontent.com/52830829/146635196-6c44f4dd-debe-4f14-9fb1-0818b76ae918.png)

Please look into this matter.
@vigneshpalainsamy @asinghal279 @omkar-pote @raghav0108 @vignespacap

**Comment by vignespacap** [comment]
Hi @Preetmungara . Thanks for notifying this issue.

kindly verify once again you followed with bellow steps.
https://github.com/omkar-pote/count-cuckoo#building-locally

```
- git clone https://github.com/omkar-pote/count-cuckoo.git
- npm i
- npm run build
```

https://github.com/omkar-pote/count-cuckoo#installing-on-chrome

-Go to Chrome extensions **chrome://extensions/**
-Enable Developer mode
-Select the "Load Unpacked" option and point to the **build** directory


Also, Kindly help us with more info. 
Your System Os and Browser Details.

**Comment by preetmungara** [comment]
Issue was this [on windows].

![sshot-014](https://user-images.githubusercontent.com/52830829/146722240-3e4da128-867b-4f97-9b8d-e05bb3f2e97d.png)

Adding this **"build": "set \"INLINE_RUNTIME_CHUNK=false\" && react-scripts build",** 
 in place of    **"build": "INLINE_RUNTIME_CHUNK=false react-scripts build",** in package.json worked for me. 

Works like charm 🔥🔥

**Comment by vignespacap** [comment]
Thanks @Preetmungara
